[package]
name = "anthropic-rs-probe"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
hyper = { version = "0.14", features = ["client", "http1", "stream"] }
hyper-rustls = "0.24"
isahc = "1"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "native-tls"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }
